name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Check format with stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          args: --check .
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: Lint with selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          args: --display-style=quiet .
          token: ${{ secrets.GITHUB_TOKEN }}
